// Code generated by "stringer -type=nodeTypeT"; DO NOT EDIT.

package markdown

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[_NODE_PARAGRAPH-0]
	_ = x[_NODE_LINE_SPACE-1]
	_ = x[_NODE_LINK-2]
	_ = x[_NODE_LINK_LABEL-3]
	_ = x[_NODE_LINK_URL-4]
	_ = x[_NODE_CODE_INLINE-5]
	_ = x[_NODE_CODE_BLOCK-6]
	_ = x[_NODE_QUOTE-7]
	_ = x[_NODE_HEADING_0-8]
	_ = x[_NODE_HEADING_1-9]
	_ = x[_NODE_HEADING_2-10]
	_ = x[_NODE_HEADING_3-11]
	_ = x[_NODE_HEADING_4-12]
	_ = x[_NODE_HEADING_5-13]
	_ = x[_NODE_HEADING_6-14]
	_ = x[_NODE_LIST_BULLET-15]
	_ = x[_NODE_LIST_NUMBERED-16]
	_ = x[_NODE_LIST_CHECK_TRUE-17]
	_ = x[_NODE_LIST_CHECK_FALSE-18]
	_ = x[_NODE_TABLE-19]
	_ = x[_NODE_TABLE_ROW-20]
	_ = x[_NODE_TABLE_CELL-21]
	_ = x[_NODE_IMAGE-22]
}

const _nodeTypeT_name = "_NODE_PARAGRAPH_NODE_LINE_SPACE_NODE_LINK_NODE_LINK_LABEL_NODE_LINK_URL_NODE_CODE_INLINE_NODE_CODE_BLOCK_NODE_QUOTE_NODE_HEADING_0_NODE_HEADING_1_NODE_HEADING_2_NODE_HEADING_3_NODE_HEADING_4_NODE_HEADING_5_NODE_HEADING_6_NODE_LIST_BULLET_NODE_LIST_NUMBERED_NODE_LIST_CHECK_TRUE_NODE_LIST_CHECK_FALSE_NODE_TABLE_NODE_TABLE_ROW_NODE_TABLE_CELL_NODE_IMAGE"

var _nodeTypeT_index = [...]uint16{0, 15, 31, 41, 57, 71, 88, 104, 115, 130, 145, 160, 175, 190, 205, 220, 237, 256, 277, 299, 310, 325, 341, 352}

func (i nodeTypeT) String() string {
	if i < 0 || i >= nodeTypeT(len(_nodeTypeT_index)-1) {
		return "nodeTypeT(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _nodeTypeT_name[_nodeTypeT_index[i]:_nodeTypeT_index[i+1]]
}
