Shell:
  #Default:  [ murex ]
  Fallback: [ /bin/sh ]

Terminal:
  TypeFace:
    FontName: ""
    FontSize: 14
    DropShadow: true
  ScrollbackHistory: 10000 # lines
  JumpScrollLineCount: 2

Window:
  Opacity: 90