Shell:
  Default:  [ murex   ]
  Fallback: [ /bin/sh ]

Terminal:
  TypeFace:
    FontName: ""
    FontSize: 12
    DropShadow: true
  ScrollbackHistory: 10000 # lines
  JumpScrollLineCount: -1  # lines, 0 is per character, -1 is per page
  RefreshInterval: 200 # 0 disables

Window:
  Opacity: 100 # %age