Shell:
  Default:  [ murex   ]
  Fallback: [ /bin/sh ]

Terminal:
  TypeFace:
    #FontName: "Hasklig-Regular"
    FontSize: 14
    Ligatures: true # increases system requirements
    #DropShadow: true
    AdjustCellWidth:  0
    AdjustCellHeight: +1
  ScrollbackHistory: 100000 # lines
  ScrollbackCloseKeyPress: true # close scrollback on key press
  JumpScrollLineCount: -1  # lines, 0 is per character, -1 is per page
  #LightMode: true # experimental
  
  Widgets:
    Table:
      ScrollMultiplierX: 2
      ScrollMultiplierY: 2


Window:
  Opacity: 90 # percentage
  StatusBar: true
  RefreshInterval: 200     # 0 disables

Tmux:
  Enabled: true 
