// This file is auto-generated by go generate. DO NOT EDIT.

export const REDRAW_OP = {
    CELL: 1,
    FRAME: 2,
    HIGHLIGHT_RECT: 3,
    RECT_COLOUR: 4,
    BLOCK_CHROME: 5,
    GAUGE_H: 6,
    GAUGE_V: 7,
    TILE_OVERLAY: 8,
    IMAGE: 9,
    TABLE: 10,
};

export const REDRAW_FLAG = {
    BOLD: 1,
    ITALIC: 2,
    UNDERLINE: 4,
    STRIKE: 8,
    SEARCH_RESULT: 16,
    FOLDED: 32,
};
