// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {jupyter} from '../models';
import {notes} from '../models';
import {types} from '../models';
import {grep} from '../models';
import {lsp} from '../models';
import {swagger} from '../models';

export function AskAI(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CancelNotesListFiles():Promise<void>;

export function CloseNotification(arg1:number):Promise<void>;

export function CommandPaletteSelect(arg1:number):Promise<void>;

export function CompleteSyntax(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number,arg6:number,arg7:string):Promise<main.CompleteSyntaxReturnT>;

export function ComposeNoteLocationPath(arg1:string,arg2:string):Promise<string>;

export function DeleteFile(arg1:string):Promise<void>;

export function DisplayHyperlinkMenu(arg1:string,arg2:string):Promise<void>;

export function FilterStrings(arg1:string,arg2:Array<string>):Promise<Array<string>>;

export function FocusTerminalPane():Promise<void>;

export function FormatCodeBlock(arg1:string,arg2:string,arg3:string,arg4:string):Promise<jupyter.FormatCodeReturnT>;

export function FormatCodeFile(arg1:string,arg2:string):Promise<void>;

export function GetAllLanguageDescriptions():Promise<Array<string>>;

export function GetAppTitle():Promise<string>;

export function GetClipboardData():Promise<main.ClipboardData>;

export function GetCurrentGroupName():Promise<string>;

export function GetCurrentProject():Promise<string>;

export function GetCustomRegexp():Promise<Array<Record<string, string>>>;

export function GetDocumentCache(arg1:string):Promise<notes.DocumentCacheT>;

export function GetFile(arg1:string):Promise<main.GetFileReturnT>;

export function GetFileMetaMarkdown(arg1:string):Promise<string>;

export function GetHyperlinkMenuActions(arg1:string,arg2:string):Promise<Array<Record<string, any>>>;

export function GetImage(arg1:string):Promise<string>;

export function GetLanguageDescriptions(arg1:string):Promise<Array<string>>;

export function GetNotesColumnWidths(arg1:string,arg2:string,arg3:Array<string>,arg4:boolean):Promise<Array<number>>;

export function GetNotesLanguageReservedWords(arg1:string):Promise<Array<string>>;

export function GetNotesLanguageTabIndent(arg1:string):Promise<number>;

export function GetNotesMaxLogLines():Promise<number>;

export function GetProjectCache():Promise<notes.ProjectCacheT>;

export function GetTerminalGlyphSize():Promise<types.XY>;

export function GetWindowStyle():Promise<main.WindowStyleT>;

export function HyperlinkOpenWithDefault(arg1:string):Promise<void>;

export function ListFiles():Promise<Array<string>>;

export function NotesGrepStream(arg1:string,arg2:grep.Options):Promise<void>;

export function NotesHistoryAdd(arg1:string):Promise<void>;

export function NotesHistoryCurrent():Promise<string>;

export function NotesHistoryNext():Promise<string>;

export function NotesHistoryPrevious():Promise<string>;

export function NotesKeyPress(arg1:string,arg2:boolean,arg3:boolean,arg4:boolean,arg5:boolean):Promise<Record<string, boolean>>;

export function NotesLspApplyCodeAction(arg1:string,arg2:number,arg3:number,arg4:number,arg5:Array<lsp.Diagnostic>):Promise<lsp.ApplyCodeActionResult>;

export function NotesLspChangeDocument(arg1:string,arg2:string):Promise<void>;

export function NotesLspCloseDocument(arg1:string):Promise<void>;

export function NotesLspCodeActions(arg1:string,arg2:number,arg3:number,arg4:Array<lsp.Diagnostic>):Promise<Array<lsp.CodeActionItem>>;

export function NotesLspCodeLens(arg1:string):Promise<Array<lsp.CodeLensItem>>;

export function NotesLspCompletion(arg1:string,arg2:number,arg3:number,arg4:number,arg5:string):Promise<Array<lsp.CompletionItem>>;

export function NotesLspDefinition(arg1:string,arg2:number,arg3:number):Promise<Array<lsp.DefinitionLocation>>;

export function NotesLspDocumentSymbols(arg1:string):Promise<Array<lsp.DocumentSymbolItem>>;

export function NotesLspExecuteCodeLens(arg1:string,arg2:number):Promise<boolean>;

export function NotesLspFormat(arg1:string):Promise<lsp.FormatResult>;

export function NotesLspFormatRange(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number):Promise<lsp.FormatResult>;

export function NotesLspHover(arg1:string,arg2:number,arg3:number):Promise<string>;

export function NotesLspInlayHints(arg1:string):Promise<Array<lsp.InlayHintItem>>;

export function NotesLspOpenDocument(arg1:string,arg2:string,arg3:string):Promise<void>;

export function NotesLspPrepareRename(arg1:string,arg2:number,arg3:number):Promise<lsp.PrepareRenameResult>;

export function NotesLspRename(arg1:string,arg2:number,arg3:number,arg4:string):Promise<lsp.RenameResult>;

export function NotesLspSaveDocument(arg1:string):Promise<void>;

export function NotesLspSemanticTokens(arg1:string):Promise<Array<lsp.SemanticTokenItem>>;

export function NotesLspSignatureHelp(arg1:string,arg2:number,arg3:number,arg4:number,arg5:string):Promise<string>;

export function NotesLspStopAll():Promise<void>;

export function NotesLspWorkspaceSymbols(arg1:string,arg2:string):Promise<Array<lsp.WorkspaceSymbolItem>>;

export function NotesRecentFiles():Promise<Array<string>>;

export function NotesSpellCheck(arg1:string):Promise<Array<main.SpellCheckSuggestionT>>;

export function RenameFile(arg1:string,arg2:string):Promise<void>;

export function ResolveFilePath(arg1:string):Promise<string>;

export function ResolveNoteLocation(arg1:string):Promise<string>;

export function ResolveNotesLspLanguage(arg1:string):Promise<string>;

export function RunAIAgentWithStream(arg1:string,arg2:string):Promise<void>;

export function RunFunction(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<string>,arg6:string):Promise<main.RunFunctionReturnT>;

export function RunHyperlinkMenuAction(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RunNote(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SaveBinaryFile(arg1:string,arg2:string):Promise<void>;

export function SaveFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveImageDialog(arg1:string):Promise<string>;

export function SendIpc(arg1:string,arg2:Record<string, string>):Promise<void>;

export function SendToTerminal(arg1:string):Promise<void>;

export function SetDocumentCache(arg1:string,arg2:notes.DocumentCacheT):Promise<void>;

export function SetNotesColumnWidths(arg1:string,arg2:string,arg3:Array<string>,arg4:boolean,arg5:Array<number>):Promise<void>;

export function SetProjectCache(arg1:notes.ProjectCacheT):Promise<void>;

export function ShowCommandPalette():Promise<void>;

export function StopNote(arg1:string):Promise<void>;

export function SwaggerRequest(arg1:swagger.RequestT):Promise<swagger.ResponseT>;

export function TerminalCopyImageDataURL(arg1:string):Promise<void>;

export function TerminalGetTabs():Promise<Array<Record<string, any>>>;

export function TerminalInputBoxSubmit(arg1:number,arg2:types.InputBoxCallbackResultT,arg3:boolean):Promise<void>;

export function TerminalKeyPress(arg1:string,arg2:boolean,arg3:boolean,arg4:boolean,arg5:boolean):Promise<void>;

export function TerminalMenuCancel(arg1:number,arg2:number):Promise<void>;

export function TerminalMenuHighlight(arg1:number,arg2:number):Promise<void>;

export function TerminalMenuSelect(arg1:number,arg2:number):Promise<void>;

export function TerminalMouseButton(arg1:number,arg2:number,arg3:number,arg4:number,arg5:boolean):Promise<void>;

export function TerminalMouseMotion(arg1:number,arg2:number,arg3:number,arg4:number,arg5:number):Promise<void>;

export function TerminalMouseWheel(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function TerminalRequestRedraw():Promise<void>;

export function TerminalResize(arg1:number,arg2:number):Promise<void>;

export function TerminalSelectWindow(arg1:string):Promise<void>;

export function TerminalSetFocus(arg1:boolean):Promise<void>;

export function TerminalSetGlyphSize(arg1:number,arg2:number):Promise<void>;

export function TerminalTextInput(arg1:string):Promise<void>;

export function ViewFileInNotes():Promise<void>;

export function WindowHide():Promise<void>;

export function WindowPrint():Promise<void>;

export function WindowShow():Promise<void>;

export function WindowShowHide():Promise<void>;
