// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMarkdown() {
  return window['go']['main']['WApp']['GetMarkdown']();
}

export function GetParameters() {
  return window['go']['main']['WApp']['GetParameters']();
}

export function GetPayload() {
  return window['go']['main']['WApp']['GetPayload']();
}

export function GetWindowStyle() {
  return window['go']['main']['WApp']['GetWindowStyle']();
}

export function GetWindowType() {
  return window['go']['main']['WApp']['GetWindowType']();
}

export function VisualInputBox(arg1) {
  return window['go']['main']['WApp']['VisualInputBox'](arg1);
}
