// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {types} from '../models';
import {swagger} from '../models';

export function AddToFileList(arg1:string):Promise<void>;

export function DeleteFile(arg1:string):Promise<void>;

export function GetAllLanguageDescriptions():Promise<Array<string>>;

export function GetAppTitle():Promise<string>;

export function GetClipboardData():Promise<main.ClipboardData>;

export function GetCustomRegexp():Promise<Array<Record<string, string>>>;

export function GetImage(arg1:string):Promise<string>;

export function GetLanguageDescriptions(arg1:string):Promise<Array<string>>;

export function GetMarkdown(arg1:string):Promise<string>;

export function GetTerminalGlyphSize():Promise<types.XY>;

export function GetWindowStyle():Promise<main.WindowStyleT>;

export function ListFiles():Promise<Array<string>>;

export function RenameFile(arg1:string,arg2:string):Promise<void>;

export function RunAIAgentWithStream(arg1:string,arg2:string):Promise<void>;

export function RunNote(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SaveBinaryFile(arg1:string,arg2:string):Promise<void>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SaveImageDialog(arg1:string):Promise<string>;

export function SendIpc(arg1:string,arg2:Record<string, string>):Promise<void>;

export function SendToTerminal(arg1:string):Promise<void>;

export function StopNote(arg1:string):Promise<void>;

export function SwaggerRequest(arg1:swagger.RequestT):Promise<swagger.ResponseT>;

export function TerminalCopyImageDataURL(arg1:string):Promise<void>;

export function TerminalGetTabs():Promise<Array<Record<string, any>>>;

export function TerminalInputBoxSubmit(arg1:number,arg2:string,arg3:boolean):Promise<void>;

export function TerminalKeyPress(arg1:string,arg2:boolean,arg3:boolean,arg4:boolean,arg5:boolean):Promise<void>;

export function TerminalMenuCancel(arg1:number,arg2:number):Promise<void>;

export function TerminalMenuHighlight(arg1:number,arg2:number):Promise<void>;

export function TerminalMenuSelect(arg1:number,arg2:number):Promise<void>;

export function TerminalMouseButton(arg1:number,arg2:number,arg3:number,arg4:number,arg5:boolean):Promise<void>;

export function TerminalMouseMotion(arg1:number,arg2:number,arg3:number,arg4:number,arg5:number):Promise<void>;

export function TerminalMouseWheel(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function TerminalRequestRedraw():Promise<void>;

export function TerminalResize(arg1:number,arg2:number):Promise<void>;

export function TerminalSelectWindow(arg1:string):Promise<void>;

export function TerminalSetFocus(arg1:boolean):Promise<void>;

export function TerminalSetGlyphSize(arg1:number,arg2:number):Promise<void>;

export function TerminalTextInput(arg1:string):Promise<void>;

export function WindowHide():Promise<void>;

export function WindowPrint():Promise<void>;

export function WindowShow():Promise<void>;

export function WindowShowHide():Promise<void>;
