// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AskAI(arg1, arg2, arg3) {
  return window['go']['main']['WApp']['AskAI'](arg1, arg2, arg3);
}

export function CancelNotesListFiles() {
  return window['go']['main']['WApp']['CancelNotesListFiles']();
}

export function CloseNotification(arg1) {
  return window['go']['main']['WApp']['CloseNotification'](arg1);
}

export function CommandPaletteSelect(arg1) {
  return window['go']['main']['WApp']['CommandPaletteSelect'](arg1);
}

export function CompleteSyntax(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['WApp']['CompleteSyntax'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function ComposeNoteLocationPath(arg1, arg2) {
  return window['go']['main']['WApp']['ComposeNoteLocationPath'](arg1, arg2);
}

export function DeleteFile(arg1) {
  return window['go']['main']['WApp']['DeleteFile'](arg1);
}

export function DisplayHyperlinkMenu(arg1, arg2) {
  return window['go']['main']['WApp']['DisplayHyperlinkMenu'](arg1, arg2);
}

export function FocusTerminalPane() {
  return window['go']['main']['WApp']['FocusTerminalPane']();
}

export function FormatCodeBlock(arg1, arg2, arg3, arg4) {
  return window['go']['main']['WApp']['FormatCodeBlock'](arg1, arg2, arg3, arg4);
}

export function FormatCodeFile(arg1, arg2) {
  return window['go']['main']['WApp']['FormatCodeFile'](arg1, arg2);
}

export function GetAllLanguageDescriptions() {
  return window['go']['main']['WApp']['GetAllLanguageDescriptions']();
}

export function GetAppTitle() {
  return window['go']['main']['WApp']['GetAppTitle']();
}

export function GetClipboardData() {
  return window['go']['main']['WApp']['GetClipboardData']();
}

export function GetCurrentGroupName() {
  return window['go']['main']['WApp']['GetCurrentGroupName']();
}

export function GetCurrentProject() {
  return window['go']['main']['WApp']['GetCurrentProject']();
}

export function GetCustomRegexp() {
  return window['go']['main']['WApp']['GetCustomRegexp']();
}

export function GetDocumentCache(arg1) {
  return window['go']['main']['WApp']['GetDocumentCache'](arg1);
}

export function GetFile(arg1) {
  return window['go']['main']['WApp']['GetFile'](arg1);
}

export function GetFileMetaMarkdown(arg1) {
  return window['go']['main']['WApp']['GetFileMetaMarkdown'](arg1);
}

export function GetHyperlinkMenuActions(arg1, arg2) {
  return window['go']['main']['WApp']['GetHyperlinkMenuActions'](arg1, arg2);
}

export function GetImage(arg1) {
  return window['go']['main']['WApp']['GetImage'](arg1);
}

export function GetLanguageDescriptions(arg1) {
  return window['go']['main']['WApp']['GetLanguageDescriptions'](arg1);
}

export function GetProjectCache() {
  return window['go']['main']['WApp']['GetProjectCache']();
}

export function GetTerminalGlyphSize() {
  return window['go']['main']['WApp']['GetTerminalGlyphSize']();
}

export function GetWindowStyle() {
  return window['go']['main']['WApp']['GetWindowStyle']();
}

export function ListFiles() {
  return window['go']['main']['WApp']['ListFiles']();
}

export function NotesHistoryAdd(arg1) {
  return window['go']['main']['WApp']['NotesHistoryAdd'](arg1);
}

export function NotesHistoryCurrent() {
  return window['go']['main']['WApp']['NotesHistoryCurrent']();
}

export function NotesHistoryNext() {
  return window['go']['main']['WApp']['NotesHistoryNext']();
}

export function NotesHistoryPrevious() {
  return window['go']['main']['WApp']['NotesHistoryPrevious']();
}

export function NotesKeyPress(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['WApp']['NotesKeyPress'](arg1, arg2, arg3, arg4, arg5);
}

export function NotesLspApplyCodeAction(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['WApp']['NotesLspApplyCodeAction'](arg1, arg2, arg3, arg4, arg5);
}

export function NotesLspChangeDocument(arg1, arg2) {
  return window['go']['main']['WApp']['NotesLspChangeDocument'](arg1, arg2);
}

export function NotesLspCloseDocument(arg1) {
  return window['go']['main']['WApp']['NotesLspCloseDocument'](arg1);
}

export function NotesLspCodeActions(arg1, arg2, arg3, arg4) {
  return window['go']['main']['WApp']['NotesLspCodeActions'](arg1, arg2, arg3, arg4);
}

export function NotesLspCodeLens(arg1) {
  return window['go']['main']['WApp']['NotesLspCodeLens'](arg1);
}

export function NotesLspCompletion(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['WApp']['NotesLspCompletion'](arg1, arg2, arg3, arg4, arg5);
}

export function NotesLspDefinition(arg1, arg2, arg3) {
  return window['go']['main']['WApp']['NotesLspDefinition'](arg1, arg2, arg3);
}

export function NotesLspDocumentSymbols(arg1) {
  return window['go']['main']['WApp']['NotesLspDocumentSymbols'](arg1);
}

export function NotesLspExecuteCodeLens(arg1, arg2) {
  return window['go']['main']['WApp']['NotesLspExecuteCodeLens'](arg1, arg2);
}

export function NotesLspFormat(arg1) {
  return window['go']['main']['WApp']['NotesLspFormat'](arg1);
}

export function NotesLspFormatRange(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['WApp']['NotesLspFormatRange'](arg1, arg2, arg3, arg4, arg5);
}

export function NotesLspHover(arg1, arg2, arg3) {
  return window['go']['main']['WApp']['NotesLspHover'](arg1, arg2, arg3);
}

export function NotesLspInlayHints(arg1) {
  return window['go']['main']['WApp']['NotesLspInlayHints'](arg1);
}

export function NotesLspOpenDocument(arg1, arg2, arg3) {
  return window['go']['main']['WApp']['NotesLspOpenDocument'](arg1, arg2, arg3);
}

export function NotesLspPrepareRename(arg1, arg2, arg3) {
  return window['go']['main']['WApp']['NotesLspPrepareRename'](arg1, arg2, arg3);
}

export function NotesLspRename(arg1, arg2, arg3, arg4) {
  return window['go']['main']['WApp']['NotesLspRename'](arg1, arg2, arg3, arg4);
}

export function NotesLspSaveDocument(arg1) {
  return window['go']['main']['WApp']['NotesLspSaveDocument'](arg1);
}

export function NotesLspSemanticTokens(arg1) {
  return window['go']['main']['WApp']['NotesLspSemanticTokens'](arg1);
}

export function NotesLspSignatureHelp(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['WApp']['NotesLspSignatureHelp'](arg1, arg2, arg3, arg4, arg5);
}

export function NotesLspStopAll() {
  return window['go']['main']['WApp']['NotesLspStopAll']();
}

export function NotesLspWorkspaceSymbols(arg1, arg2) {
  return window['go']['main']['WApp']['NotesLspWorkspaceSymbols'](arg1, arg2);
}

export function NotesRecentFiles() {
  return window['go']['main']['WApp']['NotesRecentFiles']();
}

export function RenameFile(arg1, arg2) {
  return window['go']['main']['WApp']['RenameFile'](arg1, arg2);
}

export function ResolveFilePath(arg1) {
  return window['go']['main']['WApp']['ResolveFilePath'](arg1);
}

export function ResolveNoteLocation(arg1) {
  return window['go']['main']['WApp']['ResolveNoteLocation'](arg1);
}

export function ResolveNotesLspLanguage(arg1) {
  return window['go']['main']['WApp']['ResolveNotesLspLanguage'](arg1);
}

export function RunAIAgentWithStream(arg1, arg2) {
  return window['go']['main']['WApp']['RunAIAgentWithStream'](arg1, arg2);
}

export function RunFunction(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['WApp']['RunFunction'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function RunHyperlinkMenuAction(arg1, arg2, arg3) {
  return window['go']['main']['WApp']['RunHyperlinkMenuAction'](arg1, arg2, arg3);
}

export function RunNote(arg1, arg2, arg3, arg4) {
  return window['go']['main']['WApp']['RunNote'](arg1, arg2, arg3, arg4);
}

export function SaveBinaryFile(arg1, arg2) {
  return window['go']['main']['WApp']['SaveBinaryFile'](arg1, arg2);
}

export function SaveFile(arg1, arg2, arg3) {
  return window['go']['main']['WApp']['SaveFile'](arg1, arg2, arg3);
}

export function SaveImageDialog(arg1) {
  return window['go']['main']['WApp']['SaveImageDialog'](arg1);
}

export function SendIpc(arg1, arg2) {
  return window['go']['main']['WApp']['SendIpc'](arg1, arg2);
}

export function SendToTerminal(arg1) {
  return window['go']['main']['WApp']['SendToTerminal'](arg1);
}

export function SetDocumentCache(arg1, arg2) {
  return window['go']['main']['WApp']['SetDocumentCache'](arg1, arg2);
}

export function SetProjectCache(arg1) {
  return window['go']['main']['WApp']['SetProjectCache'](arg1);
}

export function ShowCommandPalette() {
  return window['go']['main']['WApp']['ShowCommandPalette']();
}

export function StopNote(arg1) {
  return window['go']['main']['WApp']['StopNote'](arg1);
}

export function SwaggerRequest(arg1) {
  return window['go']['main']['WApp']['SwaggerRequest'](arg1);
}

export function TerminalCopyImageDataURL(arg1) {
  return window['go']['main']['WApp']['TerminalCopyImageDataURL'](arg1);
}

export function TerminalGetTabs() {
  return window['go']['main']['WApp']['TerminalGetTabs']();
}

export function TerminalInputBoxSubmit(arg1, arg2, arg3) {
  return window['go']['main']['WApp']['TerminalInputBoxSubmit'](arg1, arg2, arg3);
}

export function TerminalKeyPress(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['WApp']['TerminalKeyPress'](arg1, arg2, arg3, arg4, arg5);
}

export function TerminalMenuCancel(arg1, arg2) {
  return window['go']['main']['WApp']['TerminalMenuCancel'](arg1, arg2);
}

export function TerminalMenuHighlight(arg1, arg2) {
  return window['go']['main']['WApp']['TerminalMenuHighlight'](arg1, arg2);
}

export function TerminalMenuSelect(arg1, arg2) {
  return window['go']['main']['WApp']['TerminalMenuSelect'](arg1, arg2);
}

export function TerminalMouseButton(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['WApp']['TerminalMouseButton'](arg1, arg2, arg3, arg4, arg5);
}

export function TerminalMouseMotion(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['WApp']['TerminalMouseMotion'](arg1, arg2, arg3, arg4, arg5);
}

export function TerminalMouseWheel(arg1, arg2, arg3, arg4) {
  return window['go']['main']['WApp']['TerminalMouseWheel'](arg1, arg2, arg3, arg4);
}

export function TerminalRequestRedraw() {
  return window['go']['main']['WApp']['TerminalRequestRedraw']();
}

export function TerminalResize(arg1, arg2) {
  return window['go']['main']['WApp']['TerminalResize'](arg1, arg2);
}

export function TerminalSelectWindow(arg1) {
  return window['go']['main']['WApp']['TerminalSelectWindow'](arg1);
}

export function TerminalSetFocus(arg1) {
  return window['go']['main']['WApp']['TerminalSetFocus'](arg1);
}

export function TerminalSetGlyphSize(arg1, arg2) {
  return window['go']['main']['WApp']['TerminalSetGlyphSize'](arg1, arg2);
}

export function TerminalTextInput(arg1) {
  return window['go']['main']['WApp']['TerminalTextInput'](arg1);
}

export function ViewFileInNotes() {
  return window['go']['main']['WApp']['ViewFileInNotes']();
}

export function WindowHide() {
  return window['go']['main']['WApp']['WindowHide']();
}

export function WindowPrint() {
  return window['go']['main']['WApp']['WindowPrint']();
}

export function WindowShow() {
  return window['go']['main']['WApp']['WindowShow']();
}

export function WindowShowHide() {
  return window['go']['main']['WApp']['WindowShowHide']();
}
