// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dispatcher} from '../models';

export function DeleteFile(arg1:string):Promise<void>;

export function GetImage(arg1:string):Promise<string>;

export function GetMarkdown(arg1:string):Promise<string>;

export function GetParameters():Promise<any>;

export function GetWindowStyle():Promise<dispatcher.WindowStyleT>;

export function GetWindowType():Promise<string>;

export function ListFiles():Promise<Array<string>>;

export function RenameFile(arg1:string,arg2:string):Promise<void>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SendIpc(arg1:string,arg2:Record<string, string>):Promise<void>;

export function VisualInputBox(arg1:string):Promise<void>;
